name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest

    name: '${{ matrix.config.name }}'
    runs-on: '${{ matrix.config.os }}'

    steps:
      - uses: actions/checkout@v4

      # This officially handles downloading the CLI and exporting paths automatically
      - name: Setup Geode CLI
        uses: geode-sdk/cli/.github/actions/setup@main

      # Standard clean native CMake building pipeline
      - name: Configure CMake
        run: |
          cmake -B build
        shell: bash

      - name: Build Mod Binaries
        run: |
          cmake --build build --config Release
        shell: bash
