name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Geode CLI
        uses: geode-sdk/cli/.github/actions/setup@main

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_PREFIX_PATH="~/.geode/sdk"
        shell: pwsh

      - name: Build Mod Binaries
        run: |
          cmake --build build --config Release
        shell: pwsh

  build-mac:
    name: macOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Geode CLI
        uses: geode-sdk/cli/.github/actions/setup@main

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_PREFIX_PATH="~/Library/Application Support/Geode/sdk"
        shell: bash

      - name: Build Mod Binaries
        run: |
          cmake --build build --config Release
        shell: bash
