name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest

    name: '${{ matrix.config.name }}'
    runs-on: '${{ matrix.config.os }}'

    steps:
      - uses: actions/checkout@v4

      # This downloads the CLI and installs the SDK to standard user profile paths
      - name: Setup Geode CLI
        uses: geode-sdk/cli/.github/actions/setup@main

      # Explicitly pointing CMAKE_PREFIX_PATH to the newly installed SDK solves the find_package error
      - name: Configure CMake
        run: |
          if [ "${ { matrix.config.os }}" = "windows-latest" ]; then
            cmake -B build -DCMAKE_PREFIX_PATH="${HOME}/.geode/sdk"
          else
            cmake -B build -DCMAKE_PREFIX_PATH="${HOME}/Library/Application Support/Geode/sdk"
          fi
        shell: bash

      - name: Build Mod Binaries
        run: |
          cmake --build build --config Release
        shell: bash
